name        : dmxproto
version     : 2.3.1
release     : 4
source      :
    - http://xorg.freedesktop.org/releases/individual/proto/dmxproto-2.3.1.tar.gz : 3262bbf5902211a3ce88f5c6ab4528145ff84f69c52fd386ae0312bc45fb8a40
license     :
    - MIT
summary     : Distributed Multihead X (DMX) Extension
component   : xorg.proto
patterns    : /
description : |
    This extension defines a protocol for clients to access a front-end proxy
    X server that controls multiple back-end X servers making up a large display.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
